<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="TreeSitter.DotNet" Version="1.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="tree-sitter-sourcepawn.dll" CopyToOutputDirectory="PreserveNewest" Condition="Exists('tree-sitter-sourcepawn.dll')" />
    <None Include="tree-sitter-sourcepawn.so" CopyToOutputDirectory="PreserveNewest" Condition="Exists('tree-sitter-sourcepawn.so')" />
    <None Include="tree-sitter-sourcepawn.dylib" CopyToOutputDirectory="PreserveNewest" Condition="Exists('tree-sitter-sourcepawn.dylib')" />
  </ItemGroup>

</Project>
