void test()
{
    if(a)
    {
        if(b)
        {
            if(c)
            {
                if(d)
                {
                    if(e)
                    {
                        if(f)
                        {
                            DoSomething();
                        }
                    }
                }
            }
        }
    }
}